
P2r DEFINITIONS AUTOMATIC TAGS ::= BEGIN

ProtocolVersion ::= SEQUENCE {
    major-version INTEGER(0..32),
    minor-version INTEGER(0..64)
}

ConnectionId ::= SEQUENCE {
	fp-id INTEGER(0..255),
    rm-id INTEGER(0..255)
}

MessageType ::= INTEGER(0..255)

Message ::= SEQUENCE {
    protocol-version ProtocolVersion,
    messageType MessageType,
    connection-id ConnectionId,
    parameters Parameters
}

id-p2r-connection-setup-request MessageType ::= 1
id-p2r-connection-setup-response MessageType ::= 2
id-p2r-connection-release MessageType ::= 3
id-p2r-connection-release-ack MessageType ::= 4
id-p2r-session-termination-warning MessageType ::= 5
id-p2r-session-termination-warning-ack MessageType ::= 6
id-p2r-session-termination-warning-cancel MessageType ::= 7
id-p2r-session-restore-warning MessageType ::= 8
id-p2r-session-restore-warning-ack MessageType ::= 9

Cause ::= ENUMERATED {undefined, success, timeout, error, no-resources, ... }
Reason ::= ENUMERATED { unknown, planned, unplanned, ...}

P2RConnectionSetupResponse ::= SEQUENCE {
    cause Cause
}

P2RConnectionRelease ::= SEQUENCE {
    reason UTF8String
}

P2RConnectionReleaseAck ::= SEQUENCE {
    cause Cause
}

P2RSessionTerminationWarning ::= SEQUENCE {
    warning-id INTEGER(0..65535),
    reason Reason,
    estimated-time INTEGER(0..255)
}

P2RSessionTerminationWarningAck ::= SEQUENCE {
    cause Cause
}

P2RSessionTerminationWarningCancel ::= SEQUENCE {
    warning-id INTEGER(0..65535)
}

P2RSessionRestoreWarning ::= SEQUENCE {
   estimated-time INTEGER(0..255)
}

P2RSessionRestoreWarningAck ::= SEQUENCE {
    cause Cause
}

Parameters ::= CHOICE {
        connection-setup-request NULL,
        connection-setup-response P2RConnectionSetupResponse,
        connection-release P2RConnectionRelease,
        connection-release-ack P2RConnectionReleaseAck,
        session-termination-warning P2RSessionTerminationWarning,
        session-termination-warning-ack P2RSessionTerminationWarningAck,
        session-termination-warning-cancel P2RSessionTerminationWarningCancel,
        session-restore-warning P2RSessionRestoreWarning,
        session-restore-warning-ack P2RSessionRestoreWarningAck
}

END